version: "3.8"                                                           # 파일 규격 버전

services:                                                                # 컨테이너 정의
  docker-depl-database:                                                  # 서비스명
    container_name: docker-depl-database                                 # 컨테이너 명
    build:
      dockerfile: Dockerfile
      context: dockerfiles/database
    image: epikeran/docker-depl-database
    environment:
      - MYSQL_DATABASE=dockerdepl
      - MYSQL_ROOT_PASSWORD=${SPRING_DATASOURCE_PASSWORD}
    volumes:
      - ./dockerfiles/database/config/my.cnf:/etc/mysql/conf.d/my.cnf
    ports:
      - "3306:3306"                                                      # 접근 포트 설정 (컨테이너 외부:컨테이너 내부)
  docker-depl-app:
    container_name: docker-depl-app
    build: .
    depends_on:                                                          # DB 컨테이너가 실행된 다음 WEB 을 실행
      - docker-depl-database
    image: epikeran/docker-depl-app
    environment:
      - SPRING_DATASOURCE_USERNAME=${SPRING_DATASOURCE_USERNAME}
      - SPRING_DATASOURCE_PASSWORD=${SPRING_DATASOURCE_PASSWORD}
      - SPRING_PROFILES_ACTIVE=${SPRING_PROFILES_ACTIVE}
    ports:
      - "80:8080"
#    restart: always # depends on 은 실행순서만 컨트롤 함
    # DB 컨테이너가 실행가는 상태가 아니여서 실패하는 경우 재시작 하도록 설정